### PR TITLE
Bump rust-polars to 0.35

### PR DESCRIPTION
**Pull request by etiennebacher**
https://github.com/pola-rs/polars/releases/tag/rs-0.35.0

### CODE REVIEW

**Comment by etiennebacher** [comment]
Nice to see the upstream polars becoming more robust, it was much faster than before to update. 

There are some additional improvements that we could add here, in particular:
* https://github.com/pola-rs/polars/pull/11973 for `$name$to_lowercase() and `$name$to_uppercase()`
* https://github.com/pola-rs/polars/pull/12179 (doesn't change anything on the rust side)

They are not blockers for this PR though

**Comment by sorhawell** [comment]
This is PR is really nice! I don't know why (windows-latest, oldrel-1) is failing due to no pak. Perhaps it is a temp r-lib bug. I suggest to disable (windows-latest, oldrel-1) and follow that in a separate PR.

**Review by sorhawell — APPROVED** [review]

**Comment by eitsupi** [comment]
Perhaps it has something to do with the fact that a new version of pak was released yesterday?
How about just ignoring the failures?

**Review by eitsupi — APPROVED** [review]
Great work! Thanks.

**Pull request merged**
