### PR TITLE
Add `pl$LazyFrame()`

### LINKED ISSUE #242: Make a function `LazyFrame()`?
It would be convenient to create a `LazyFrame` like `pl$LazyFrame()` (basically just a wrapper for `pl$DataFrame()$lazy()`). It can be done with Python Polars: https://pola-rs.github.io/polars/py-polars/html/reference/lazyframe/index.html#lazyframe

### PR DESCRIPTION
**Pull request by etiennebacher**
Close #242 

``` r
library(polars)

new <- pl$LazyFrame(mtcars)

new$collect()
#> shape: (32, 11)
#> ┌──────┬─────┬───────┬───────┬───┬─────┬─────┬──────┬──────┐
#> │ mpg  ┆ cyl ┆ disp  ┆ hp    ┆ … ┆ vs  ┆ am  ┆ gear ┆ carb │
#> │ ---  ┆ --- ┆ ---   ┆ ---   ┆   ┆ --- ┆ --- ┆ ---  ┆ ---  │
#> │ f64  ┆ f64 ┆ f64   ┆ f64   ┆   ┆ f64 ┆ f64 ┆ f64  ┆ f64  │
#> ╞══════╪═════╪═══════╪═══════╪═══╪═════╪═════╪══════╪══════╡
#> │ 21.0 ┆ 6.0 ┆ 160.0 ┆ 110.0 ┆ … ┆ 0.0 ┆ 1.0 ┆ 4.0  ┆ 4.0  │
#> │ 21.0 ┆ 6.0 ┆ 160.0 ┆ 110.0 ┆ … ┆ 0.0 ┆ 1.0 ┆ 4.0  ┆ 4.0  │
#> │ 22.8 ┆ 4.0 ┆ 108.0 ┆ 93.0  ┆ … ┆ 1.0 ┆ 1.0 ┆ 4.0  ┆ 1.0  │
#> │ 21.4 ┆ 6.0 ┆ 258.0 ┆ 110.0 ┆ … ┆ 1.0 ┆ 0.0 ┆ 3.0  ┆ 1.0  │
#> │ …    ┆ …   ┆ …     ┆ …     ┆ … ┆ …   ┆ …   ┆ …    ┆ …    │
#> │ 15.8 ┆ 8.0 ┆ 351.0 ┆ 264.0 ┆ … ┆ 0.0 ┆ 1.0 ┆ 5.0  ┆ 4.0  │
#> │ 19.7 ┆ 6.0 ┆ 145.0 ┆ 175.0 ┆ … ┆ 0.0 ┆ 1.0 ┆ 5.0  ┆ 6.0  │
#> │ 15.0 ┆ 8.0 ┆ 301.0 ┆ 335.0 ┆ … ┆ 0.0 ┆ 1.0 ┆ 5.0  ┆ 8.0  │
#> │ 21.4 ┆ 4.0 ┆ 121.0 ┆ 109.0 ┆ … ┆ 1.0 ┆ 1.0 ┆ 4.0  ┆ 2.0  │
#> └──────┴─────┴───────┴───────┴───┴─────┴─────┴──────┴──────┘
```

### CODE REVIEW

**Review by eitsupi — CHANGES_REQUESTED** [review]
Thanks!

Could you format the files?
(`make fmt GIT_DIF_TARGET=main` may helping)

**Comment by etiennebacher** [comment]
Doesn't work for me:
```
> make fmt GIT_DIF_TARGET=main
Error: unexpected end of input
Execution halted
cargo fmt --manifest-path src/rust/Cargo.toml
```

**Comment by etiennebacher** [comment]
Looks like it's fine with `cargo fmt --manifest-path ./src/rust/Cargo.toml` (note the `./`)

**Comment by eitsupi** [comment]
What is your OS?

**Comment by etiennebacher** [comment]
Windows 10

**Comment by eitsupi** [comment]
I see...

Anyway, this PR should not require Rust formatting, so try `make fmt-r GIT_DIF_TARGET=main`.

**Comment by etiennebacher** [comment]
If it helps, here's how we apply `lintr` to modified files only in `easystats` packages: https://github.com/easystats/workflows/blob/main/.github/workflows/lint-changed-files.yaml

**Comment by etiennebacher** [comment]
```
$ make fmt-r GIT_DIF_TARGET=main
Error: unexpected end of input
Execution halted
make: Nothing to be done for 'fmt-r'.
```
is this expected?

**Comment by eitsupi** [comment]
Hmmm, it may not work correctly on Windows because it was written without taking into account how it works on Windows.

**Comment by eitsupi** [comment]
@etiennebacher I don't know how the Makefile specifying shell to bash works on Windows.
https://github.com/pola-rs/r-polars/blob/9fc2772c032c7c1411256d57b0fe2680a896931c/Makefile#L3

On which shell are you exec the `make` command?

**Review by eitsupi — APPROVED** [review]

**Comment by etiennebacher** [comment]
I tried both the default Terminal in RStudio and a bash shell. Note that even with `make docs` for example, I have this error message but then the command still properly runs:
```
Error: unexpected end of input
Execution halted
Rscript -e 'if (!(require(arrow)&&require(nanoarrow))) warning("could not load arrow/nanoarrow, igonore changes to nanoarrow.Rd"); rextendr::document()'
```

**Comment by eitsupi** [comment]
The `fmt-r` command includes command calls such as R and grep and foreach and I am not sure if these will work properly on Windows or on Bash on MinGW which is included in R on Windows.

https://github.com/pola-rs/r-polars/blob/9fc2772c032c7c1411256d57b0fe2680a896931c/Makefile#L79-L83

**Comment by etiennebacher** [comment]
Thanks for the review, I have to leave now but I'll try to come back to this in the next few days (it's not urgent, I can just run `styler` on the full package)

**Comment by eitsupi** [comment]
Styler is really slow...
And even worse here, it is twice as slow because it runs the styler twice to change `<-` to `=`...
(That's why I implemented a command to format only changed files based on git diff)

**Pull request merged**
