### PR TITLE
release: version 0.19.1

### PR DESCRIPTION
**Pull request by etiennebacher**

### CODE REVIEW

**Comment by eitsupi** [comment]
Perhaps you are tagging the wrong commit, as the commit tagged v0.19.1 is actually v0.19.0.

**Comment by etiennebacher** [comment]
Ah, do you know if I can change the tagget commit or do I need to delete the release and make a new one?

**Comment by eitsupi** [comment]
We need to delete the release on the GitHub, and then delete the tag on GitHub afterwards.
Then push the tag again to create the release.

**Comment by eitsupi** [comment]
@etiennebacher Perhaps you misunderstand the release process. Could you please check carefully how the tags have been tagged in the past and re-release them?

**Comment by eitsupi** [comment]
I will remake the release as this is causing the CI in the downstream repository to break and needs an urgent fix.

**Comment by etiennebacher** [comment]
Sorry about that, I may have misunderstood those steps in DEVELOPMENT.md:

> 1. Create a local branch for the release, push it to the remote repository (main
>  repository), then open a pull request to the `main` branch.
> 2. Bump the R package version with the `usethis` package.
>
> ```r
> usethis::use_version()
> # Please choose `major`, `minor` or `patch`
> ```
> 
> 3. Check the CI status of the pull request.
> 4. Push a tag named starting with `v` (e.g. `v0.10.0`). It triggers the GitHub
>   action to build the website and create a GitHub release.
> 5. Bump the R package version to "dev version" with the `usethis` package
>   before merging the pull request.

When I created the `v0.19.1` tag in the Github interface, I forgot to change the target from "main" to the branch created in step 1.

**Pull request merged**
