### PR TITLE
Misc improvements in docs

### PR DESCRIPTION
**Pull request by etiennebacher**
* Fix some typos
* Improve R docs
* Fix light theme colors (CI uses `mkdocs` 1.4.2 and I had 1.3.1)
* Rename CI file
* Add "Copy code" buttons to code blocks

### CODE REVIEW

**Comment by vincentarelbundock** [comment]
I noticed a few dead links in README and perhaps other documentation places.

* https://rpolars.github.io/reference/Expr_cos.html
  - New format: https://rpolars.github.io/reference/Expr_cos
  - There might be more of these in the docs
* https://rpolars.github.io/articles/polars.html
  - New format: https://rpolars.github.io/articles/polars/ (last forward slash is important)
* How do we link the main reference page? I think it might be nice to add a landing page for the reference which briefly describes the main categories...

**Comment by sorhawell** [comment]
I was building docs from scratch

@etiennebacher I was following above guide to build docs

```R
pak::local_install_deps(dependencies = c("all", "Config/Needs/website"))
pak::pak(c("etiennebacher/altdoc", "yaml", "magrittr", "cli", "tinkr", "stringr", "Genentech/rd2markdown@c4fb386"))
altdoc::update_docs(custom_reference = "docs/make-docs.R")
Error in if (.doc_type == "mkdocs") { : argument is of length zero
```

I think the error went away when I copied file `mkdocs.orig.yml` to `mkdocs.yml`

silly question how do I launch the docs as complete webpage?

**Comment by etiennebacher** [comment]
> I noticed a few dead links in README and perhaps other documentation places.

Thanks, I fixed some of the links but the link to `Expr` in reference will likely change because I want to create a specific "Expr" subsection and maybe add more subsubsections there like in [py-polars](https://pola-rs.github.io/polars/py-polars/html/reference/expressions/aggregation.html).

>  How do we link the main reference page? I think it might be nice to add a landing page for the reference which briefly describes the main categories...

Agreed, I'll look into it

> I think the error went away when I copied file mkdocs.orig.yml to mkdocs.yml. 

@sorhawell That shouldn't happen and it works fine for me. Note that this only works if your working directory is the root of the package (e.g it doesn't work if your `getwd()` is "C:/.../r-polars/docs"). Can you also tell me if you're using VS code? 

> silly question how do I launch the docs as complete webpage?

`altdoc::preview()` should be enough, and even if it doesn't open the page directly it prints the localhost in the console

**Comment by eitsupi** [comment]
> That shouldn't happen and it works fine for me.

mkdocs.yml is gitignored and needs to be generated only once the first time.
Once generated, that step is no longer necessary as it will remain.

**Comment by etiennebacher** [comment]
> > That shouldn't happen and it works fine for me.
> 
> mkdocs.yml is gitignored and needs to be generated only once the first time. Once generated, that step is no longer necessary as it will remain.

Ah right, I think this will be taken care of in the makefile (cf #177)

**Comment by eitsupi** [comment]
I noticed that the code blocks don't show the copy button.
Could you please enable this?
https://squidfunk.github.io/mkdocs-material/reference/code-blocks/

**Comment by sorhawell** [comment]
@etiennebacher  I tried to build and view docs via @eitsupi new make shortcuts. It worked fast, flawless and was easy :)

**Comment by etiennebacher** [comment]
Regarding the "Reference" landing page, I'm not sure what it should look like. If it's just a page that says

```
The functions are categorized as follows:

* DataFrame: all operations applicable on DataFrames
* LazyFrame: all operations applicable on LazyFrames
* etc.
```

with links to relevant sections, then it doesn't bring much. @vincentarelbundock do you have an example in mind of what this landing page should look like? (it can be a page that we manually edit, not necessarily something auto-generated from the Rd files)

**Comment by etiennebacher** [comment]
Some things like splitting `Expr` in subsections and the reference landing page might take some time to implement and I'll be a bit busy in the next few days or weeks (of course feel free to implement them yourselves). I think this can be merged already (once errors are fixed) as it improves a bit the docs quality and we won't be able to fix everything at once.

**Review by vincentarelbundock — COMMENTED** [review]
Looks great! Would you mind just adding a quasi-empty landing page for the reference page? If we merge your PR including the empty landing page, I'll fill it and address some of the other issues in #182 in a separate PR.

**Review by eitsupi — APPROVED** [review]
Thanks, looks good!
I added some minor changes.

The table display corrupt when I preview it locally, is it only for me?
image

**Comment by etiennebacher** [comment]
@vincentarelbundock I added an almost empty file for the reference homepage but you will need to uncomment the code I added in `convert_hierarchy_to_yml()` in `make-docs.R` to include it automatically in `mkdocs.yml` (so that it's not included in the deployed docs while it's empty). I tested and it looks like this for now:

image

**Comment by etiennebacher** [comment]
> The table display corrupt when I preview it locally, is it only for me?

@eitsupi I don't have this on laptop but I have this kind of preview on mobile (which is less of an issue for me)

**Comment by eitsupi** [comment]
Yes, thanks to your fixes in the previous PR, the currently deployed website displays correctly for me.
But not in the documentation built from this branch...
Well, it's not a big problem.

**Comment by vincentarelbundock** [comment]
FWIW, the tables in this branch look good on my local computer.

Thanks @etiennebacher for the dummy landing page.

No need to wait for further approval on my end. Thanks for the work!

**Pull request merged**
