### PR TITLE
pin rust night in release.yaml (follow up #217)

### LINKED ISSUE #216: rust polars doesn't support the latest Rust nightly toolchain
Build currently fails due to compatibility with 2023-05-13 nightly toolchain.
https://github.com/pola-rs/r-polars/blob/6a3522d11ddbbba9dc739918e9ee4d1ca2c10bcf/src/rust/rust-toolchain#L2
https://github.com/pola-rs/r-polars/blob/6a3522d11ddbbba9dc739918e9ee4d1ca2c10bcf/Makefile#L34-L36

Definitely need to specify a date like this.
https://github.com/pola-rs/polars/blob/64dabba165a811179197687f193037daba1103c1/rust-toolchain.toml#L2

Unfortunately, there does not seem to be a command to install the toolchain by referencing a rust-toolchain file at this time (rust-lang/rustup#2686), so it appears that the date needs to be entered in the two places above.

### PR DESCRIPTION
**Pull request by sorhawell**
Close #216

### CODE REVIEW

**Comment by sorhawell** [comment]
@eitsupi 
I could not find anywhere in docs to pin rust. Is it always using a cached version of compilation only? Would that always work?

**Comment by sorhawell** [comment]
#216

**Comment by eitsupi** [comment]
> I could not find anywhere in docs to pin rust. Is it always using a cached version of compilation only? Would that always work?

Just using `make` command here.

https://github.com/pola-rs/r-polars/blob/bd2e7b9d3c2ea83ace051bca6ad220fcf690e88c/.github/workflows/docs.yaml#L90-L91

I have updated this PR to use `make` in other workflows.
Now we only need to specify the toolchain version in one place.

**Comment by eitsupi** [comment]
@sorhawell Are the following sections still needed?
My understanding is that we are using `Swatinem/rust-cache` and don't need it anymore.
https://github.com/pola-rs/r-polars/blob/f95214fb4cd49674d975b6c216400d369a038cb7/src/Makevars#L23-L29

**Review by eitsupi — APPROVED** [review]
New cache workflow seems working fine, so merging now.

**Comment by sorhawell** [comment]
@eitsupi I think long time ago  R CMD check gave warnings for illegal files in the target lib.  It is probably not needed anymore. If we run into that again we can rewrite it accordingly.

**Comment by eitsupi** [comment]
Sorry, I was mistaken.
Perhaps what is needed is the following process.
It may easier to detect the `NOT_CRAN` environment variable and change the behavior.
I believe the latest rextendr's template does that.

https://github.com/r-rust/hellorust/blob/05a148ff4128a2480d3519a19bd5cbcd9efcbe2e/src/Makevars#L16-L19

```makefile
$(STATLIB):
	PATH="${PATH}:${HOME}/.cargo/bin" cargo build --release --manifest-path=myrustlib/Cargo.toml
	rm -Rf $(CARGOTMP) || true #CRAN wants us to remove "detritus"
	rm -Rf $(LIBDIR)/build || true
```

**Pull request merged**
