### PR TITLE
Implement `Enum` datatype

### LINKED ISSUE #668: Support Enum data type
See pola-rs/polars#11822

### PR DESCRIPTION
**Pull request by etiennebacher**
Close #668

### CODE REVIEW

**Review by eitsupi — APPROVED** [review]
Thanks!

**Comment by eitsupi** [comment]
@etiennebacher Do you think it is ok to do the release work after this has been merged?

**Comment by etiennebacher** [comment]
Would it be for 0.16.2 or 0.17.0? If 0.16.2 yes, but if 0.17.0 we can merge #1050 and #1053 first

**Comment by eitsupi** [comment]
Sorry for the confusion, I meant 0.16.2.
I think 0.17.0 would be good after Rust Polars 0.40.0 release, as the polars repository shows some breaking changes merged after 0.39.2.

**Pull request merged**
