### PR TITLE
fix: support Rust 1.65

### LINKED ISSUE #208: R-universe r-polars build fails because rust-polars is no longer backwards compatible with rustc 1.65.0 stable
R-universe build fails
https://github.com/r-universe/rpolars/actions/runs/4884403053

~~I tried to downgrade to rust 1.65 stable locally, but I got no errors so far.~~
~~Something with simd is mentioned in some of the compiler errrors, but not sure what it is about.~~

EDIT: In a clean build I was able to reproduce the error by downgrading to rustc 1.65 stable

### PR DESCRIPTION
**Pull request by sorhawell**
Fix #208

### CODE REVIEW

**Comment by sorhawell** [comment]
@eitsupi  not sure whylinker cant find rpolars.a, but it does compile on 1.65.0 on my machine if `RPOLARS_ALL_FEATURES != 'true`

**Comment by eitsupi** [comment]
Nice! It seems passing the MSRV check.

**Comment by sorhawell** [comment]
> Nice! It seems passing the MSRV check.

changing cargo-toml from 1.66 to 1.65 now it should be more impressive :)

**Comment by eitsupi** [comment]
> changing cargo-toml from 1.66 to 1.65 now it should be more impressive :)

Thanks, it seems passing!

**Comment by eitsupi** [comment]
> The output for each profile will be placed in a directory of the same name as the profile in the [target directory](https://doc.rust-lang.org/cargo/guide/build-cache.html). As in the example above, the output would go into the target/release-lto directory.

https://doc.rust-lang.org/cargo/reference/profiles.html#custom-profiles

**Comment by eitsupi** [comment]
Given the need to make significant changes to Makevars if adding `profile.release-optimized`, I suspect that simply setting `profile.release.package.argminmax` is sufficient.

**Review by eitsupi — APPROVED** [review]
I think it can be merged now.

**Comment by eitsupi** [comment]
@sorhawell Can I merge this and go ahead?

**Comment by sorhawell** [comment]
Ohh profile changes output dir, that was what I was missing . Thanks @eitsupi  , looks good!

**Pull request merged**
