### PR TITLE
docs(news): tweak NEWS.md

### PR DESCRIPTION
**Pull request by eitsupi**

### CODE REVIEW

**Comment by eitsupi** [comment]
Hmm Markdownlint and Mkdocs seem to be incompatible.......

**Review by etiennebacher — APPROVED** [review]
Can you check whether this is fine on the rendered website?

**Comment by eitsupi** [comment]
> Can you check whether this is fine on the rendered website?

Yes, of course I checked locally.

image

As an aside, it would be useful to have an option to render only the NEWS.md file and skip the execution of the man file.
pkgdown have functions to render only certain files, I believe.

**Comment by etiennebacher** [comment]
For now we only have `freeze = TRUE` to skip files that didn't change

**Comment by eitsupi** [comment]
> For now we only have `freeze = TRUE` to skip files that didn't change

Yes, I have used it and seen the results. However, right after deleting the generated files, we need to wait until all man pages are rendered.

```r
altdoc::render_docs(freeze = TRUE, parallel = TRUE, verbose = TRUE)
```

**Pull request merged**
