### PR TITLE
docs: increase font size for code

### PR DESCRIPTION
**Pull request by etiennebacher**
Mostly changes the navbar color and make the dark theme slightly less dark

### Light theme

**Before:**

image

**After:**

image

### Dark theme

**Before:**

image

**After:**

image

### CODE REVIEW

**Comment by eitsupi** [comment]
I prefer the current monochrome theme if anything. (No strong opinions, however.)

**Comment by etiennebacher** [comment]
Interesting, I find the current dark theme a bit... sad 😄 nice to see different opinions

**Comment by sorhawell** [comment]
I think it is beautiful. No strong oppions. Please try any theme :)

**Review by eitsupi — APPROVED** [review]
Do you want to merge for now?
If so, I'm happy to merge at any time you like.

**Comment by etiennebacher** [comment]
I'll try a few more things first

**Comment by etiennebacher** [comment]
In the end I just increase a bit the font size both for inline code and for code blocks, and fixed a few `groupby()` that I forgot in another PR.

**Pull request merged**
