### PR TITLE
chore: switch to the edge version (0.6.x) of extendr-api

### LINKED ISSUE #418: Should we install the fork version of extendr?
A new version of extendr was recently released.

We are currently using a forked extendr, is this still necessary?
https://github.com/pola-rs/r-polars/blob/2d2aaa7386e869b53a55e4be11d3ea974d52de86/src/rust/Cargo.toml#L37-L40

### PR DESCRIPTION
**Pull request by eitsupi**
Close #418

### CODE REVIEW

**Comment by eitsupi** [comment]
I saw these errors now:

```log
   error[E0616]: field `0` of struct `Rfloat` is private
     --> src/conversion_r_to_s.rs:80:35
      |
   80 |                         let x = x.0.to_bits() as i64;
      |                                   ^ private field
   
   error[E0616]: field `0` of struct `Rfloat` is private
      --> src/conversion_r_to_s.rs:102:66
       |
   102 |                     .map(|x| if x.is_na() { None } else { Some(x.0) })
       |                                                                  ^ private field
   
   error[E0616]: field `0` of struct `Rint` is private
      --> src/conversion_r_to_s.rs:142:66
       |
   142 |                     .map(|x| if x.is_na() { None } else { Some(x.0) })
       |                                                                  ^ private field
   
   error[E0616]: field `0` of struct `Rfloat` is private
      --> src/utils/mod.rs:107:32
       |
   107 |                 Ok(Some(rvalue.0))
       |                                ^ private field
       |
      ::: src/series.rs:396:28
       |
   396 |                 Float64 => apply_output!(r_iter, strict, allow_fail_eval, Doubles, Float64Chunked),
       |                            ----------------------------------------------------------------------- in this macro invocation
       |
       = note: this error originates in the macro `handle_type` which comes from the expansion of the macro `apply_output` (in Nightly builds, run with -Z macro-backtrace for more info)
   
   error[E0616]: field `0` of struct `Rint` is private
      --> src/utils/mod.rs:118:28
       |
   118 |             let val = rint.0;
       |                            ^ private field
       |
      ::: src/series.rs:397:26
       |
   397 |                 Int32 => apply_output!(r_iter, strict, allow_fail_eval, Integers, Int32Chunked),
       |                          ---------------------------------------------------------------------- in this macro invocation
       |
       = note: this error originates in the macro `handle_type` which comes from the expansion of the macro `apply_output` (in Nightly builds, run with -Z macro-backtrace for more info)
```

@sorhawell Sorry for bothering you, but do you know about this?

**Comment by sorhawell** [comment]
No problem :)

Try using .inner()

https://github.com/extendr/extendr/issues/584

**Comment by sorhawell** [comment]
I think this PR, even as is brings good value and simplifies our fork.

I hope this "result_list patch " will be merged in to exgtendr-api.

Very nice work @eitsupi.

**Comment by eitsupi** [comment]
I'm ok to merge this at this stage.
Once extendr/extendr#652 is merged, we can change the reference.

**Review by sorhawell — APPROVED** [review]

**Pull request merged**
