### PR TITLE
docs(website): fix indentation in changelog

### PR DESCRIPTION
**Pull request by etiennebacher**
Currently nested lists are flattened, this fixes it

### CODE REVIEW

**Comment by eitsupi** [comment]
Does this mean altdoc or something is expecting an indent size of 4?
In that case, I think we need to force the indent size using something like Editorconfig.

**Comment by etiennebacher** [comment]
I think this is just required by `mkdocs`. The NEWS file in `altdoc` has nested lists with only 2 spaces and it works fine with the `docute` generator

>  In that case, I think we need to force the indent size using something like Editorconfig.

I'm not familiar with this, does it work with any IDE?

**Comment by eitsupi** [comment]
> I'm not familiar with this, does it work with any IDE?

Yes, except for RStudio IDE. (rstudio/rstudio#1711)

**Comment by etiennebacher** [comment]
@eitsupi I don't know how to enable Editorconfig, so feel free to merge this when ready

**Review by eitsupi — APPROVED** [review]
Looks fine, thanks!

**Comment by eitsupi** [comment]
This is the upstream issue https://github.com/mkdocs/mkdocs/issues/545#issuecomment-522196661

**Pull request merged**
