### PR TITLE
`to_vector()` and `to_data_frame()`

### PR DESCRIPTION
**Pull request by vincentarelbundock**
Closes https://github.com/pola-rs/r-polars/issues/117

* `to_r_vector()` -> `to_vector()`
* `as_data_frame()` -> `to_data_frame()`

I added aliases to both functions with `@noRd` tags to preserve backward compatibility, and I have added ultra-minimalist tests of `as_data_frame()` and `to_r_vector()` to make sure we don't break old code.

This is a lot of changes, but it was basically just a search and replace with minimal other changes.

### CODE REVIEW

**Comment by vincentarelbundock** [comment]
FWIW, @sorhawell suggested `$to_data_frame()` in the issue linked above, and I liked that suggestion a lot, which is why I implemented that. I personally don't think it's confusing, and would prefer that to `to_r_data_frame()`, which I find verbose and not too pretty.

Not a big fan of `to_r()` because wouldn't be certain what kind of R object this returns.

**Comment by eitsupi** [comment]
> Not a big fan of `to_r()` because wouldn't be certain what kind of R object this returns.

I agree with that, but python-polars has `to_pandas` and `to_arrow`......

I looked again and found that python-polars has `polars.Series.to_frame`.
https://pola-rs.github.io/polars/py-polars/html/reference/series/api/polars.Series.to_frame.html

Considering this, I still think the name `$to_data_frame` is not a good choice here.

**Comment by vincentarelbundock** [comment]
> I agree with that, but python-polars has `to_pandas` and `to_arrow`......

Right. Note that these are not `to_python_pandas` and `to_python_arrow`, which would be analogous to `to_r_data_frame`.

In any case, I made my pitch and am now happy to defer this decision to the package creator(s).

**Comment by vincentarelbundock** [comment]
Cool. I think I'm still unconvinced, but I agree with you that this is not such a big deal.

**Comment by sorhawell** [comment]
many thx @vincentarelbundock

**Pull request merged**
