### PR TITLE
chore: additional updates due to package name change

### PR DESCRIPTION
**Pull request by eitsupi**
Some additional updates due to package name change.

### CODE REVIEW

**Comment by eitsupi** [comment]
This may affect other PRs, so merge now.

**Comment by sorhawell** [comment]
did we get the news right now @vincentarelbundock ?

**Comment by sorhawell** [comment]
thx @eitsupi  💯

**Comment by vincentarelbundock** [comment]
No, the news was not updated unfortunately.

**Comment by sorhawell** [comment]
@eitsupi would it make sense to not update `news` manaually for each PR.
I could instead copy over auto generated release notes from github release mechanism.

@vincentarelbundock

**Comment by eitsupi** [comment]
I rather prefer to manually add only the changes that are important to the user to the NEWS file.

I suppose the NEWS file could be updated manually and the release notes to be included in the GitHub release could be generated automatically.

**Pull request merged**
