### PR TITLE
Add `$rolling_*_by()` expressions

### LINKED ISSUE #1082: split out rolling_*(..., by='foo') into rolling_*_by('foo', ...)
Same as pola-rs/polars#16059

### PR DESCRIPTION
**Pull request by etiennebacher**
Part of #1108, close #1082

### CODE REVIEW

**Comment by eitsupi** [comment]
@etiennebacher What is the current status of this? When do you expect to be able to merge it?

**Comment by etiennebacher** [comment]
There are missing `rolling_*_by()` for `var`, `std` and `quantile`.

I think I should be able to address them by the end of the week (but feel free to update this PR if you want).

**Comment by eitsupi** [comment]
Related issue about argument name pola-rs/polars#16684

**Review by eitsupi — APPROVED** [review]
I seems working now.

**Comment by etiennebacher** [comment]
Thanks for finishing this one @eitsupi

**Pull request merged**
