### PR TITLE
Documentation tweaks

### PR DESCRIPTION
**Pull request by vincentarelbundock**
Preview: http://arelbundock.com/polars

This PR is a refactor of the `make_docs.R` script. Roughly speaking, the current script works like this:

1. Read `.Rd` files
2. Convert `.Rd` files to `.md` files using the `rd2markdown` package.
3. Use `mkdocs` to convert those `.md` files back to `.html` files and build the website.

The multiple conversions are a bit convoluted and risky, as some things may be lost during translation. This workflow also relies on the `rd2markdown` package, which is only available and apparently has bugs: not all documentation section are displayed, and the order is shuffled.

This PR changes the workflow to:

1. Read `.Rd` files.
2. Convert `.Rd` files to `.html` using base R `tools::Rd2HTML`.
3. Embed this html code directly in the `.md` files that `makedocs` reads.

With a few tweaks, this PR gives us:

- [x] Code simplification: `make_docs.R` is 40% shorter.
- [x] No more dependencies on `cli`, `tinkr`, `magrittr`, `stringr`, `fs`, and the problematic `rd2markdown`.
- [x] All sections of the `.Rd` files are displayed in the correct order.
- [x] Nice display of the Arguments section in a table.
- [x] Polars User Guide page.
- [x] About page.
- [x] Simple (naive?) way to control order of Reference menu.
- [x] Nested menu for `Expr`
- [x] Functions are sorted in sections using function names or `@name` tags.

TODO:

- [x] Usage as `<DataFrame>$columns`
- [x] Argument names are sometimes wrapped when they should not be.
- [ ] Code highlighting of the Usage section.
- [x] Go through the reference menu to identify problematic cases.
- [x] Large space in Examples code block
- [x] Missing usage in `pl_DateTime` and others
- [ ] Landing page
- [x] the header for each reference should be the title of the Rd file and not the function name. For example, here (https://arelbundock.com/polars/reference/DataFrame_columns/) we should remove the "columns" at the top of the page (like how it currently is in the deployed docs)
  
I would appreciate any and all comments

### CODE REVIEW

**Comment by vincentarelbundock** [comment]
tag @etiennebacher who might be interested.

**Comment by etiennebacher** [comment]
Impressive work, this refactoring looks really nice. I'll dive in the code a bit later but a few visual remarks so far:

* the header for each reference should be the title of the Rd file and not the function name. For example, here (https://arelbundock.com/polars/reference/DataFrame_columns/) we should remove the "columns" at the top of the page (like how it currently is)
* there's a large space at the beginning of the code block for examples. This is due to the output of `downlit` that needs to be tweaked a bit (I did that in a commit in #138 but I don't remember which one exactly)
* would be nice to replace e.g `DataFrame_columns()` by `<DataFrame>$columns()` in "Usage". You can take some code from #185 for this
* the "Usage" section is not displayed for some pages (e.g https://arelbundock.com/polars/reference/pl_Datetime/)

I love the subsections for `Expr`. Do you want to add a landing page in this PR as well or is it for later?

**Comment by vincentarelbundock** [comment]
@etiennebacher I updated the TODO list, checked off a few things, and updated the preview website.

I don't know how to change the header, but I think I actually like having the function up top.

I looked at a couple cases of missing Usage sections, and it looks like those don't have a Usage in the .Rd file itself. I guess we could add them manually in roxygen2, but I don't think the workflow is dropping them.

**Comment by etiennebacher** [comment]
Additional remarks:

1. The description text before the usage section is too big, it's the same size as section titles. 
2. For highlighting the usage section, it would have to be done before fixing the function names because `downlit` doesn't work with the `<>`:
``` r
downlit::highlight("<DataFrame>$clone()")
#> [1] NA
```
3. Regarding sections in the sidebar, I think they should be ordered alphabetically and that we should rename the `Polars` section ("Operations" maybe?).
4. I really prefer having the function title as header instead of the function name (using title as header is also what `pkgdown` does).

Finally, is it fine to push some commits in your branch or do you prefer handling this yourself?

**Comment by vincentarelbundock** [comment]
@etiennebacher I just pushed a few changes and have updated the preview: https://arelbundock.com/polars

>     1. The description text before the usage section is too big, it's the same size as section titles.

I think this is fixed now, yes?

>     2. For highlighting the usage section, it would have to be done before fixing the function names because `downlit` doesn't work with the `<>`:

Makes sense, but frankly this doesn't feel high priority to me, and I don't really have the energy.

>     3. Regarding sections in the sidebar, I think they should be ordered alphabetically and that we should rename the `Polars` section ("Operations" maybe?).

I think we should try to follow the Python/Rust section ordering, which is not alphabetical. "Operations" has the same problem as "Polars": both are too generic. Eventually, we probably want to be even closer to Python/Rust API reference, and sort the grab-bag of current "Polars" section in Input/Output, Functions, Extending the API. See: https://pola-rs.github.io/polars/py-polars/html/reference/

>     4. I really prefer having the function title as header instead of the function name (using title as header is also what `pkgdown` does).

Yes, sorry, I misunderstood the problem. You are 100% right. I already pushed a change for that, and we have proper titles now.

> Finally, is it fine to push some commits in your branch or do you prefer handling this yourself?

Yep, that's fine. I'm traveling next week, so won't be able to work on this PR anymore. I can either merge it nearly as-is, or hand it off to you to complete.

Thanks again for putting together the website. It looks super cool.

**Comment by etiennebacher** [comment]
Re title and description: yes all good now

Re code highlighting: completely agree, low priority thing

Re section organization: yes I'll try to match the organization of the Python docs more closely. Once this is done, the "Polars" section will no longer be needed 

I'd prefer working on this on a branch of `main` instead of on your fork so I can review this now and merge it. Can you fix the conflicts and request my review?

And thanks also for improving the website, adding keywords and fixing the docs is really tedious work

**Review by etiennebacher — CHANGES_REQUESTED** [review]
Actually I noticed a few things that should be fixed before merging:

* evaluation of some examples fail, e.g https://arelbundock.com/polars/reference/DataFrame_join/
* we lost the link to the source file between title and description sections
* the "About" tab doesn't need to be a vignette, we can just make it a permanent file in `docs`

@vincentarelbundock the first point is the most important and I can take care of it in this branch before deploying the docs.

**Comment by vincentarelbundock** [comment]
> Actually I noticed a few things that should be fixed before merging:
> 
>     * evaluation of some examples fail, e.g https://arelbundock.com/polars/reference/DataFrame_join/

Good catch! The problem is that I was not careful enough in doing the `<DataFrame>` sub here:
https://github.com/pola-rs/r-polars/pull/186/files#diff-ad7021ea0176aafa82074234706eef90248e9f733c463313f0dcd98f86d3f211R64

Should apply more narrowly to just the Usage section.

> @vincentarelbundock the first point is the most important and I can take care of it in this branch before deploying the docs.

Thanks! I appreciate that. Feel free to push directly to the branch. (I need to disconnect now.)

**Review by etiennebacher — APPROVED** [review]
Thanks a lot @vincentarelbundock ! This ticks several boxes in #182

**Pull request merged**
