### PR TITLE
Rollingapply

### PR DESCRIPTION
**Pull request by xendai66**

### CODE REVIEW

**Comment by sorhawell** [comment]
Hi @xendai66  , I see you are working on a new PR :)

**Comment by xendai66** [comment]
Hi @sorhawell , I was preparing for the task actually, hence I mistakenly created this pull request.

**Comment by sorhawell** [comment]
@xendai66 no worries, you are welcome to submit a "WIP" directly to main polars. Sometimes other contributors suggest help details along the way. Feel free to ask me or anyone for help, any we can suggest or even commit some edits to your PR.

**Comment by xendai66** [comment]
Hi @sorhawell, Thanks for your valuable support and suggestions. If I feel too stuck in my code, then I will definitely seek your help and others guidance as well.

**Pull request closed without merging**
