### PR TITLE
Implement `pl$mean_horizontal()` function

### PR DESCRIPTION
**Pull request by george-wood**
Proposed in #854.

### CODE REVIEW

**Comment by george-wood** [comment]
* I reverted a few changes to unrelated Rd files.
* I also added `pl$mean_horizontal()` to the @seealso of `pl$mean()` and removed the related TODO.
* I ran `task test-snapshot-accept` following the R CMD failure.

**Review by eitsupi — APPROVED** [review]
Thanks!

I have updated the Rd files and test snapshots.

**Comment by etiennebacher** [comment]
Nice, thank you @george-wood 👍 

There were a couple of minor things to improve in the docs, see the followup here: #960

**Comment by george-wood** [comment]
@etiennebacher Good improvements. I used `NaN` and `-Inf` in the tests, but not the examples. It's good to clearly show this behavior (especially for `NaN`/`null`) in #960.

**Pull request merged**
