### PR TITLE
docs: some minor fixes for the polars vignette

### PR DESCRIPTION
**Pull request by eitsupi**

### CODE REVIEW

**Review by etiennebacher — COMMENTED** [review]
We could add more details here, like "To avoid collision with classes provided by other packages, the class name of all objects created by polars starts with 'RPolars'. For example, a polars DataFrame has the class 'RPolarsDataFrame'."

**Comment by eitsupi** [comment]
> We could add more details here, like "To avoid collision with classes provided by other packages, the class name of all objects created by polars starts with 'RPolars'. For example, a polars DataFrame has the class 'RPolarsDataFrame'."

I think it would be great to add these explanations. Feel free to edit this PR.

**Comment by etiennebacher** [comment]
I moved the explanation a bit lower in the text

**Review by etiennebacher — APPROVED** [review]

**Comment by eitsupi** [comment]
Thanks!

**Pull request merged**
